[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.4.3"
tower-http = { version = "0.2.0", features = ["fs"] }
tokio = { version = "1.14.0", features = ["rt-multi-thread"] }
log = "0.4.14"
open = "2.0.2"
anyhow = "1.0.52"
